server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        - id: wishlist-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/wishlist/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
